# Generated by Django 2.2.3 on 2019-08-16 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('clipID', models.SlugField(max_length=140)),
                ('contents', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('streamer', models.CharField(max_length=140, null=True)),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clip', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
