# Generated by Django 2.2.3 on 2019-08-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='streamer',
            field=models.CharField(default=None, max_length=140, null=True),
        ),
    ]
