# Generated by Django 2.2.3 on 2019-08-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0003_auto_20190817_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyval',
            name='container',
        ),
        migrations.AddField(
            model_name='clip',
            name='streamer',
            field=models.CharField(default='None', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='title',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
