# Generated by Django 2.2.3 on 2019-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0004_auto_20190818_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clip',
            old_name='contents',
            new_name='content',
        ),
        migrations.AddField(
            model_name='clip',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='clip.Tag'),
        ),
    ]
