# Generated by Django 2.2.3 on 2019-08-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0005_auto_20190819_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='content',
            new_name='contents',
        ),
    ]
