# Generated by Django 2.2.3 on 2019-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0006_auto_20190819_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='contents',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
