# Generated by Django 2.2.3 on 2019-08-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0007_auto_20190819_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='embed_url',
            field=models.CharField(default='no embed', max_length=1000),
        ),
        migrations.AddField(
            model_name='clip',
            name='url',
            field=models.CharField(default='no url', max_length=500),
        ),
    ]
