# Generated by Django 2.2.3 on 2019-08-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0008_auto_20190825_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='clipID',
            field=models.CharField(max_length=300),
        ),
    ]
