# Generated by Django 2.2.3 on 2019-09-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0009_auto_20190901_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='embed_url',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='url',
        ),
    ]
